-- CREATES A DATABASE IF IT DOES NOT EXIST.
-- CREATES A NEW SET OF TABLES FOR USERS AND ROLES

CREATE DATABASE IF NOT EXISTS COMM;

USE COMM;

DROP TABLE IF EXISTS COMM_USER_ROLES;
DROP TABLE IF EXISTS COMM_USERS;
DROP TABLE IF EXISTS COMM_ROLES;

CREATE TABLE COMM_ROLES (
	ID INT AUTO_INCREMENT NOT NULL,
	DESCRIPTION VARCHAR(50),
	CONSTRAINT PK_ROLE_ID PRIMARY KEY(ID)
);

CREATE TABLE COMM_USERS (
	ID INT AUTO_INCREMENT NOT NULL,
	FULL_NAME VARCHAR(30) NOT NULL,
	USERNAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	CONSTRAINT PK_USER_ID PRIMARY KEY (ID)
);

CREATE TABLE COMM_USER_ROLES (
	USER_ID INT NOT NULL,
	ROLE_ID INT NOT NULL,
	CONSTRAINT PK_USER_ROLE_ID PRIMARY KEY(USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE_USER_ID  FOREIGN KEY (USER_ID) REFERENCES COMM_USERS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_USER_ROLE_ROLE_ID  FOREIGN KEY (ROLE_ID) REFERENCES COMM_ROLES(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

DESC COMM_ROLES;
DESC COMM_USERS;
DESC COMM_USER_ROLES;