-- TRUNCATES THE DATABASE.
-- POPULATES THE DATABASE WITH A SET OF VALUES

USE COMM;

DELETE FROM COMM_USER_ROLES;
DELETE FROM COMM_USERS;
DELETE FROM COMM_ROLES;

INSERT INTO COMM_ROLES (ID, DESCRIPTION) VALUES (1,'Administrator');
INSERT INTO COMM_ROLES (ID, DESCRIPTION) VALUES (2,'Customer');

INSERT INTO COMM_USERS (ID, FULL_NAME, USERNAME, PASSWORD) VALUES (1, 'Henry Smith','hsmith','smith');
INSERT INTO COMM_USERS (ID, FULL_NAME, USERNAME, PASSWORD) VALUES (2, 'Tim Bucktoo','tbucktoo','bucktoo');
INSERT INTO COMM_USERS (ID, FULL_NAME, USERNAME, PASSWORD) VALUES (3, 'Jenny Admin','jadmin','admin');

INSERT INTO COMM_USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO COMM_USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO COMM_USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 1);

SELECT * FROM COMM_ROLES;
SELECT * FROM COMM_USERS;
SELECT * FROM COMM_USER_ROLES;